const baseProducts = [
    { name: "Vanilla / 01", originalName: "Vanilla Luxe", code: "VAN/01", notes: "mandarin, citrus, soft florals, vanilla, amber, woods", shortNotes: "vanilla · amber · citrus", memory: "warm skin", description: "A smooth vanilla built around warmth and softness. Opens slightly fresh, settles into a creamy skin-like sweetness that stays close and addictive.", occasion: "daily wear, date night", price: "₹18,500", image: "../Products/VAN-01.png" },
    { name: "Oud / 09", originalName: "Oud Royal", code: "OUD/09", notes: "saffron, spice, oud, incense, leather, resin", shortNotes: "oud · saffron · leather", memory: "dark room", description: "A dense oud profile with smoky depth and controlled projection. Rich without being loud, built for presence.", occasion: "evening, formal", price: "₹24,000", image: "../Products/OUD-09.png" },
    { name: "Spice / 03", originalName: "Oriental Spice", code: "SPC/03", notes: "cardamom, cinnamon, sandalwood, amber", shortNotes: "cardamom · cinnamon · wood", memory: "warm air", description: "A warm spiced composition that feels textured and intimate. Designed to sit close and evolve slowly.", occasion: "evening, winter", price: "₹19,500", image: "../Products/SPC-03.png" },
    { name: "Skin Musk / 04", originalName: "Musk Sauvage", code: "MSK/04", notes: "bergamot, lavender, musk, vetiver", shortNotes: "bergamot · lavender · musk", memory: "fresh shirt", description: "Clean, sharp, and wearable. A skin musk that feels fresh without being basic.", occasion: "daily wear", price: "₹16,000", image: "../Products/MSK-04.png" },
    { name: "Bloom Air / 02", originalName: "Floral Fresh", code: "FLR/02", notes: "pear, rose, peony, white musk", shortNotes: "pear · rose · musk", memory: "morning light", description: "Light floral with airy projection. Fresh, soft, and easy to wear across seasons.", occasion: "daily wear", price: "₹17,500", image: "../Products/FLR-02.png" },
    { name: "White Bloom / 07", originalName: "Gucci Bloom", code: "FLR/07", notes: "tuberose, jasmine, green floral accords", shortNotes: "tuberose · jasmine · green", memory: "floral room", description: "A dense white floral that feels natural and full. Rich bloom without sharp edges.", occasion: "day, signature", price: "₹21,000", image: "../Products/FLR-07.png" },
    { name: "Sweet Paris / 11", originalName: "YSL Mon Paris", code: "FRU/11", notes: "strawberry, raspberry, peony, jasmine, patchouli, musk", shortNotes: "berry · patchouli", memory: "city night", description: "Sweet, modern fruity floral with depth from patchouli. Energetic and slightly addictive.", occasion: "night out", price: "₹19,000", image: "../Products/FRU-11.png" },
    { name: "Sport Fresh / 05", originalName: "CR7", code: "FRSH/05", notes: "citrus, lavender, spice, tonka, woods", shortNotes: "citrus · lavender · tonka", memory: "clean energy", description: "Fresh sporty scent with clean projection and easy mass appeal.", occasion: "gym, daily", price: "₹14,500", image: "../Products/FRSH-05.png" },
    { name: "Dark Amber / 12", originalName: "LV Ombre Nomade", code: "AMB/12", notes: "smoke, rose, oud, amber", shortNotes: "oud · rose · amber", memory: "desert dusk", description: "Dark, smoky, and deep. Built for strong presence and long-lasting trail.", occasion: "evening, winter", price: "₹26,500", image: "../Products/AMB-12.png" },
    { name: "Moss Wood / 02", originalName: "Cedar & Oakmoss", code: "WDS/02", notes: "cedar, oakmoss, vetiver", shortNotes: "cedar · moss · vetiver", memory: "forest floor", description: "Earthy woody profile with grounded feel. Calm and natural.", occasion: "day, office", price: "₹18,000", image: "../Products/WDS-02.png" },
    { name: "Oud Intense / 15", originalName: "Oud for Greatness", code: "OUD/15", notes: "oud, saffron, nutmeg, patchouli", shortNotes: "oud · saffron · spice", memory: "silent power", description: "Strong oud composition with spicy lift and smooth base.", occasion: "luxury, evening", price: "₹28,000", image: "../Products/OUD-15.png" },
    { name: "Red Fruit / 06", originalName: "Burberry Her", code: "FRU/06", notes: "berries, jasmine, vanilla, musk", shortNotes: "berry · vanilla", memory: "sweet trail", description: "Bright fruity gourmand with soft sweetness and modern feel.", occasion: "daily, casual", price: "₹17,000", image: "../Products/FRU-06.png" },
    { name: "Citrus Soft / 03", originalName: "Burberry Weekend", code: "CIT/03", notes: "lemon, orange, florals, musk", shortNotes: "lemon · orange · floral", memory: "slow day", description: "Relaxed citrus scent with soft projection and calm vibe.", occasion: "daytime", price: "₹15,500", image: "../Products/CIT-03.png" },
    { name: "Amber Resin / 08", originalName: "Amber Elixir", code: "AMB/08", notes: "amber, resin, vanilla", shortNotes: "amber · resin · vanilla", memory: "warm glow", description: "Deep amber scent with smooth sweetness and warmth.", occasion: "evening", price: "₹20,000", image: "../Products/AMB-08.png" },
    { name: "Pure Musk / 10", originalName: "White Musk", code: "MSK/10", notes: "white musk, aldehydes, soft florals", shortNotes: "musk · floral", memory: "clean skin", description: "Minimal clean scent that stays close and fresh.", occasion: "daily", price: "₹15,000", image: "../Products/MSK-10.png" },
    { name: "Oud Spice / 13", originalName: "Spiced Oud", code: "OUD/13", notes: "pepper, clove, oud", shortNotes: "oud · clove · pepper", memory: "warm smoke", description: "Spicy oud with sharp opening and warm drydown.", occasion: "evening", price: "₹23,000", image: "../Products/OUD-13.png" },
    { name: "Vetiver Green / 14", originalName: "Green Vetiver", code: "GRN/14", notes: "citrus, vetiver, herbs", shortNotes: "vetiver · citrus · herbs", memory: "fresh cut", description: "Green, sharp and clean. Fresh earthy profile.", occasion: "office", price: "₹16,500", image: "../Products/GRN-14.png" },
    { name: "Water Air / 16", originalName: "Aqua Marine", code: "AQUA/16", notes: "marine, citrus, salt, musk", shortNotes: "marine · citrus · salt", memory: "sea breeze", description: "Aquatic fresh scent with open airy feel.", occasion: "summer", price: "₹17,500", image: "../Products/AQUA-16.png" },
    { name: "Leather Skin / 17", originalName: "Leather Intense", code: "LTHR/17", notes: "leather, smoke, amber", shortNotes: "leather · smoke · amber", memory: "worn jacket", description: "Strong leather profile with depth and texture.", occasion: "evening", price: "₹22,000", image: "../Products/LTHR-17.png" },
    { name: "Smoke Wood / 18", originalName: "Smoky Woods", code: "SMK/18", notes: "burnt wood, incense, resin", shortNotes: "burnt wood · incense", memory: "fading fire", description: "Dry smoky scent with dark woody base.", occasion: "night", price: "₹24,500", image: "../Products/SMK-18.png" },
    { name: "Vanilla Sweet / 19", originalName: "Vanilla Rush", code: "VAN/19", notes: "vanilla, caramel, tonka", shortNotes: "vanilla · caramel · tonka", memory: "sweet comfort", description: "Rich sweet gourmand, comforting and addictive.", occasion: "casual", price: "₹18,500", image: "../Products/VAN-19.png" },
    { name: "Rose Skin / 20", originalName: "Rose Desire", code: "RSE/20", notes: "rose, pepper, musk", shortNotes: "rose · pepper · musk", memory: "soft petals", description: "Soft rose with subtle spice and skin-like finish.", occasion: "date night", price: "₹20,500", image: "../Products/RSE-20.png" }
];

let loadedProducts = [];
try {
    loadedProducts = JSON.parse(localStorage.getItem('si_products'));
} catch (e) {
    loadedProducts = null;
}

if (!loadedProducts || loadedProducts.length === 0) {
    loadedProducts = [...baseProducts];
    localStorage.setItem('si_products', JSON.stringify(baseProducts));
}

export const products = loadedProducts;
