name: Sync Admin Branch

on:
  push:
    branches:
      - main
    paths:
      - 'admin/**'

jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git Author
        run: |
          git config --global user.name "Sugandh Ink Bot"
          git config --global user.email "bot@sugandhink.in"

      - name: Push Admin subtree to admin-deploy branch
        run: |
          # Use git subtree to push only the 'admin' directory to a clean 'admin-deploy' branch
          git subtree push --prefix admin origin admin-deploy
